app-config:
  nome: Correção API
  descricao: Projeto back-end para cálculo de correções de texto.
  versao: 1.0.0
  url: http://localhost:8080/

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/correcoes-valores
    username: postgres
    password: 1y5h8j
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql

  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob.non_contextual_creation: true

authorization:
  api-secret: YmFzZTY0LWRldi1hcHAtdGF0YWlhLWNvcnJlY2FvLXRlc3Rl
  jwt-secret: dGF0YWlhLWFwaS1qd3Qtc2VjcmV0LWRldg==